# Generated by Django 4.2.1 on 2023-06-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='subname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
